# Generated by Django 4.0.5 on 2022-06-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countrymodel',
            fields=[
                ('couid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('cimg', models.ImageField(upload_to='country/')),
            ],
        ),
        migrations.CreateModel(
            name='statemodel',
            fields=[
                ('stateid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('simg', models.ImageField(upload_to='state/')),
                ('couid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.countrymodel')),
            ],
        ),
    ]
