# Generated by Django 4.0.5 on 2022-06-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='citymodel',
            fields=[
                ('cityid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ciname', models.CharField(max_length=30)),
                ('cimg', models.ImageField(upload_to='state/')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.statemodel')),
            ],
        ),
    ]
