# Generated by Django 4.0.5 on 2022-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_citymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='desc',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
    ]
