# Generated by Django 4.0.5 on 2022-06-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_citymodel_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='citygallary',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('gimg', models.ImageField(upload_to='citygallary/')),
            ],
        ),
        migrations.CreateModel(
            name='citydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citydesc', models.TextField()),
                ('citywikipedia', models.URLField()),
                ('cityyoutube', models.URLField()),
                ('citygallary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.citygallary')),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.citymodel')),
            ],
        ),
    ]
