# Generated by Django 4.0.5 on 2022-06-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_citygallary_citydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydetails',
            name='citygallary',
        ),
        migrations.AddField(
            model_name='citygallary',
            name='citydetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.citydetails'),
            preserve_default=False,
        ),
    ]
